import { BaseProto } from '../../../../../models/proto/base-proto';
import { ProtoOAExecutionType } from '../enums/ProtoOAExecutionType';
import { ProtoOABonusDepositWithdraw } from '../models/ProtoOABonusDepositWithdraw';
import { ProtoOADeal } from '../models/ProtoOADeal';
import { ProtoOADepositWithdraw } from '../models/ProtoOADepositWithdraw';
import { ProtoOAOrder } from '../models/ProtoOAOrder';
import { ProtoOAPosition } from '../models/ProtoOAPosition';

/**
 * Event that is sent following the successful order acceptance or execution by the server.
 * Acts as response to these requests:
 * ProtoOANewOrderReq,
 * ProtoOACancelOrderReq,
 * ProtoOAAmendOrderReq,
 * ProtoOAAmendPositionSLTPReq,
 * ProtoOAClosePositionReq
 *
 * Also, the event is sent when a Deposit/Withdrawal took place.
 */
export class ProtoOAExecutionEvent extends BaseProto {
    /**
     * Type of the order operation. For example: ACCEPTED, FILLED, etc.
     */
    executionType: keyof typeof ProtoOAExecutionType;

    /**
     * Reference to the position linked with the execution
     */
    position?: ProtoOAPosition;

    /**
     * Reference to the initial order.
     */
    order?: ProtoOAOrder;

    /**
     * Reference to the deal (execution).
     */
    deal?: ProtoOADeal;

    /**
     * Reference to the Bonus Deposit or Withdrawal operation.
     */
    bonusDepositWithdraw?: ProtoOABonusDepositWithdraw;

    /**
     * Reference to the Deposit or Withdrawal operation.
     */
    depositWithdraw?: ProtoOADepositWithdraw;

    /**
     * The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     */
    errorCode?: string;

    /**
     * If TRUE then the event generated by the server logic instead of the trader's request. (e.g. stop-out).
     */
    isServerEvent?: boolean;
}
